### ISSUE TITLE
better introduction please

### ISSUE THREAD

**Issue by jampy** [redux-loop/redux-loop#104]
For those not familiar with Elm (like me), could you please describe (and provide an example) how this works, so that no prior Elm knowledge is necessary?

Would be a good addition to the README.

**Comment by ttmarek** [comment]
Agreed. Just an example would go a long way.

**Comment by lukewestby** [comment]
I'm currently working with another developer to try and move the Elm concepts to the background in both the API and the documentation in order to make things more approachable to folks who are familiar with Redux but maybe not Elm. When 3.0.0 is finalized there will (hopefully) be no need for an explanation of how Elm fits in

**Comment by jtomaszewski** [comment]
Cool! The lib looks very interesting and we're thinking about picking it in our next project.

Any ETA of finalized v3?

**Comment by franzejr** [comment]
I also would like to know any ETA about V3. :)

**Comment by kachkaev** [comment]
I'm also confused. Found this repo after some experience with thunk and saga and wanted to know why I should consider `redux-loop` instead of those. But struggled to understand anything and found this issue in the end. 

An clear entry point into the suggested approach seems missing indeed.

**Comment by lukewestby** [comment]
All of these pedagogical concerns will be addressed before officially releasing 3.0.0. In the mean time you can see what we're doing in #110, although I would ask that any comments be limited to technical concerns with thorough reasoning about the implementation as it is at that time rather than suggestions about features you want to add or general differences of opinion.

However, after you take a look at what's coming and you want to suggest features please feel free to open separate issues and we'll for sure evaluate them independently of the coming release
