### ISSUE TITLE
Active development and contribution

### ISSUE THREAD

**Issue by MichalZalecki** [redux-loop/redux-loop#108]
Hi, I enjoy `redux-loop` and as we're using it in one of the production projects I'd like to discuss some changes. I'm interested in contribution making loop actions easier to test (e.g. implementing effect as Setoid to reduce test's boilerplate). Is the project still under active development, can I read about foundation for `v3`?

**Comment by lukewestby** [comment]
Hey @MichalZalecki, the upcoming changes are in #110

Just to provide you with some background, we're backing off the very FP stuff that we started in on for v3 and instead simplifying and stripping things down. That said, I think this is a good idea even if in the docs we just say that there's an `equals` function on the `Effects` type and in a footnote we can mention fantasy-land compliance with Setoid or something.

How about this for a plan: I want to get the new API merged, tested, documented and published as quickly as possible. I'm going to borrow a practice from the way we do things on https://github.com/elm-lang/core/issues and close this issue and reference it from a meta issue for 3.1.0 ideas. Once the new API is out I'll @-mention you so that you can contribute the Setoid implementation and get your name in the contributor list on GitHub.

**Comment by cpeddecord** [comment]
@lukewestby thanks for the update! <3 this lib.

**Comment by lukewestby** [comment]
@cpeddecord you're welcome! i'm excited that things are going to move forward after a little stagnation. there's been a sudden uptick in interest from various companies and individuals and i'm thankful to all of them for the effort they have put in.

**Comment by MichalZalecki** [comment]
@lukewestby Sounds good, great to see the project's moving forward!
