### ISSUE TITLE
Cannot read property type of undefined

### ISSUE THREAD

**Issue by dabit3** [redux-loop/redux-loop#109]
I'm using 3.0.0-alpha.1

```
import { Task } from 'redux-loop';

export default () => {
  return new Task((resolve, reject) => {
    setTimeout(() => {
      return (resolve(people), reject)
    }, 2000)
  })
}
```

```
case FETCHING_DATA:
      return [
        {
          ...state,
          appData: {
            isFetching: true,
            data: []
          }
        },
        getPeople()
          .perform(getDataSuccess, getDataFailure)
      ]
```
<img width="373" alt="screen shot 2017-02-19 at 8 57 29 am" src="https://cloud.githubusercontent.com/assets/1857282/23103525/eb500bb2-f681-11e6-8ad7-dbbcc30c334d.png">

Any ideas about why this may be not working for me? Thanks.

**Comment by lukewestby** [comment]
@dabit3 i'm not totally sure but rather than working through it i need to recommend that you go back to the 2.x version and stick with the `Effects.promise` function. we've decided to drop all of the extra stuff that is in the alpha and 3.0.0 api is going to be very similar to 2.x

See all of the coming changes in #110
