### ISSUE TITLE
Type definitions for TypeScript

### ISSUE THREAD

**Issue by durkiewicz** [redux-loop/redux-loop#115]
Thank you for a great library!

I'm interested in using `redux-loop` in TypeScript and I would be able to write type definitions that match this documentation: https://github.com/redux-loop/redux-loop/blob/3.0/docs/ApiDocs.md

Would you be interested in accepting a pull request with type definitions?

**Comment by lukewestby** [comment]
These are already implemented in #110 and will be coming soon. Thanks for offering to work on them though!

**Comment by farism** [comment]
It looks like a TS rewrite and definition file generator was added at [some point](https://github.com/redux-loop/redux-loop/commit/86d60e225b178134faa5697fcace6d7dec2175bb#diff-b9cfc7f2cdf78a7f4b91a753d10865a2R7) and then [removed later](https://github.com/redux-loop/redux-loop/commit/7578df7f6a64d8b6165e72060fc21efe5bc5f05f#diff-b9cfc7f2cdf78a7f4b91a753d10865a2L7) before 3.0 went out. Is any help needed for this feature?

**Comment by bdwain** [comment]
hi. yes help would be very much appreciated. I've been meaning to learn about typescript more since I have no experience with it but haven't had time yet. We went through a few API changes and the one that was in typescript is not what ended up released so any help in getting typings or converting to typescript would be very much appreciated. Please see #130 for more detail.
