### ISSUE TITLE
Just curious when 3.0 is going to be released

### ISSUE THREAD

**Issue by iamwilhelm** [redux-loop/redux-loop#117]
I'm just curious when 3.0 is going to be released (If there's even a date). I'm currently using typescript, and would like to be able to use redux-loop.

**Comment by ashishsc** [comment]
I also am curious on the current status, not to pester because I know all the hard work @lukewestby puts into the open source and Elm community. I'm hoping to get loop in place of thunk next week so I can teach my team the benefits of Elm style programming (and hopefully, eventually convince them to prototype using Elm).

**Comment by ashishsc** [comment]
I think this discussion gives a little more insight @iamwilhelm https://github.com/redux-loop/redux-loop/pull/110

Might be worth adding a not to the Readme.

**Comment by ashishsc** [comment]
Do any of the other contributors have any updates on the current state / recommended version to use? @gyzerok ? Sorry to pester

**Comment by bdwain** [comment]
Hi @iamwilhelm and @ashishsc

Sorry it's been so long since you've heard back. I'm going to be taking over maintenance of redux-loop. I'd like to get an update out in the next few days.

I know there have been a few proposed API changes in the last year. I've been using a fork of one those proposed version 3's for a while in projects that I've worked on (https://github.com/bdwain/redux-loop). I'd like to make that the starting point for any future changes. Luke and I discussed these changes last year and I think it'll be an improvement over version 2 without being too drastic of a change for people who are currently using it. It doesn't have typescript typings yet, but I would like to add that in the next few days as well.

The main idea behind the changes in my branch can be seen here [in this issue](https://github.com/redux-loop/redux-loop/issues/66) . It's passing action creators to effects/cmds instead of putting them in your side effect functions. Though since that discussion, i've consolidated some of the Cmd types.

I'll keep this issue open for now and close it when I've got everything updated. Sorry again for the delay!

**Comment by bdwain** [comment]
Version 3.0 has been released. Details can be seen [here](https://github.com/redux-loop/redux-loop/releases/tag/v3.0.0). Sorry again for the delay.

The next thing I'd like to do is get typescript support. #130 keeps track of some of the upcoming changes that are planned, so I'm going to close this in favor of that.
