### ISSUE TITLE
redux-promise and redux-loop

### ISSUE THREAD

**Issue by vvinton** [redux-loop/redux-loop#128]
Folks,

redux-promise middleware and redux-loop does not look work seamlessly together. After invoking an effect, getting Promise when expected to have resolved promise.

Here is install:
```
composeWithDevTools(
        applyMiddleware(thunk, ReduxPromise, routerMiddleware(browserHistory)),
        reduxLoopInstall()
      )
```

Here is call:
```
return loop(
          { ...settings },
          Effects.constant(getUserLocale(settings.defaultLocale))
        );
```

Here is the result:

![image](https://user-images.githubusercontent.com/2598068/27457346-13c3e258-57ad-11e7-9790-6056b1b95107.png)

Can you please help me understand how to possible workaround this?

**Comment by vvinton** [comment]
Small update on this one - I tried to set up Saga and listen to action raised from loop Effect. Saga was not able to capture it.

It looks like Loop does not tolerate middleware installed.

**Comment by bdwain** [comment]
Hi @vvinton 

Sorry it's been so long since you've heard back. I'm going to be taking over maintenance of redux-loop. The first thing I want to get is get an update out and get the documentation up to date with the latest version on npm. After that, I'd be happy to work on improving redux-loop's integration with other libraries.

**Comment by ashishsc** [comment]
I honestly don't know how I feel about using loop with other middleware. I think it makes the most sense to use it on its own rather than have several different ways to handle effects. One exception to that is that some things are potentially easier with saga (things that a state-machine isn't the best tool for, aka debounce) but you can still do it.

**Comment by alexburner** [comment]
I'm with @ashishsc on this one. There may be some redux middlewares that address unrelated concerns, and could work well alongside redux loop (such as redux persist, which I saw mentioned here https://github.com/redux-loop/redux-loop/issues/166).

However, middleware like redux promise and redux saga are trying to fix the same thing redux loop are: handling asynchronous code and other side effects (which plain redux doesn't have a good story for). It seems like all of these async solutions are mutually exclusive, I don't see why you'd want to layer them together.

Here is an overview of redux middlewares that address async code:
https://decembersoft.com/posts/what-is-the-right-way-to-do-asynchronous-operations-in-redux/
