### ISSUE TITLE
Add Redux Devtool support

### ISSUE THREAD

**Issue by ashishsc** [redux-loop/redux-loop#131]
It would be great to add support for https://github.com/gaearon/redux-devtools. Being able to see the effect deployed and have autogenerated tests would be nice.

**Comment by bdwain** [comment]
that would be cool. how would it display? just the name of the function called? and the parameter values passed to it? and maybe type of Cmd?

**Comment by ashishsc** [comment]
Yep exactly like that is what I was thinking.

**Comment by bdwain** [comment]
if anyone wants to take this on let me know. We'll probably want a new repo for it. I can create that if needed.

**Comment by gniquil** [comment]
@ashishsc and @bdwain. Check this out:

![image](https://user-images.githubusercontent.com/149100/31512604-691f1a16-af40-11e7-9495-b90f9fe70a7e.png)

(please excuse the "hello: you" business)

So this is an idea to add the list of commands to the redux devtool. The key thing is at each dispatch loop, we have an object in the enhancer that's called "cmdsQueue" that's been repopulated for execution. Currently it is a mutable variable that is local to the enahncer. However, if we do this:

```js
export function install() {
  const cmdsQueue = { queue: [] };
  return [
    cmdsQueue,
    next => (reducer, initialState, enhancer) => {
       ...
       // change cmdQueue = ... to cmdsQueue.queue = ...
    }
  ]
}
```

So here, `install()` would return a tuple of cmdsQueue object and the enhancer. Now use the enhancer as usual. however, in your dev tool integration piece, do the following:

```js
const [cmdsQueue, loopEnhancer] = install();

  const composeEnhancers = typeof window === 'object' &&
    window.__REDUX_DEVTOOLS_EXTENSION_COMPOSE__
    ? window.__REDUX_DEVTOOLS_EXTENSION_COMPOSE__({
        stateSanitizer: state => {
          return {
            ...state,
            'redux-loop-cmds': cmdsQueue.queue.map(({ cmd }) =>
              serializeCmd(cmd)
            ),
          };
        },
      })
    : compose;
```
So essentially here we serialize the commands into "state". Finally:

```js
const serializeCmd = cmd => {
  switch (cmd.type) {
    case 'RUN': {
      return {
        ...cmd,
        func: cmd.func.name,
      };
    }
    case 'LIST':
      return {
        ...cmd,
        cmds: cmd.cmds.map(serializeCmd),
      };
    case 'MAP':
      return {
        ...cmd,
        tagger: cmd.tagger.name,
        nestedCmd: serializeCmd(cmd.nestedCmd),
      };
    case 'ACTION':
    case 'NONE':
    default:
      return cmd;
  }
};
```
So here, we just have to ensure all the functions are named (so probably we need create some annotation helpers or just make sure we use `function name(...) {...}` rather than annoymous `() => ...`. 

The beauty of this is since redux-loop commands are purposely made for testing, it is inherently serializable.

**Comment by gniquil** [comment]
This is another example of getting access to the `cmdsQueue` can do. Here at work, I cleaned up the formatting a bit.

(Also note that at work we use `Cmd.map` heavily. So I also overwrote action name in the format `Action -> ChildAction -> ...`

![image](https://cdn.discordapp.com/attachments/367131029040922626/368572764338257920/unknown.png)
