### ISSUE TITLE
Improve testability of Cmd objects

### ISSUE THREAD

**Issue by jon-thompson** [redux-loop/redux-loop#137]
While it's comparatively easier to test reducers with redux-loop than with some other pieces of middleware, I do think it could be improved. Adding and removing specs for `Cmd` objects can sometimes be a little clunky, and some things are just not possible to test without inspecting the (essentially private) members of the `Cmd` object.

Some problems I run into when testing:

### 1. Action creators that take arguments

In some cases, I want a `Cmd` to dispatch an action with a predetermined argument. As it stands right now, I'd try to write a spec that looks like this:

```
expect(getCmd(reducer(state, action))).toEqual(Cmd.run(submitForm, {
  args: [Cmd.getState],
  successActionCreator: () => formSubmitted('FORM_NAME'),
}));
```

However, the above spec will always fail because `successActionCreator` is always a new function so those properties will never match. It would probably be nice to have a way for the spec to directly access `successActionCreator` so it can execute it and assert against the result. 

Possible solutions:

* A property/function on the `Cmd` object that returns the action creators
* A helper function like `getCmd` that returns the action creators

### 2. Multiple commands in the same loop

I often find myself adding and removing commands from a loop, so I prefer to have one test/assert per command. That is a little challenging with `redux-loop` as it is now though, because we only have the `Cmd` object to work with so we have to assert all commands at the same time. I currently use the `cmds` property on the `Cmd.batch` object but I don't think that is truly supported and is less than ideal because `Cmd.run` does not have a `cmds` property.

Possible solutions:

* A supported property/function on the `Cmd` object that returns an array of the commands (regardless of the object's type)
* A helper function like `getCmd` that returns all the commands, regardless of how they were grouped

I'd love to be able to do something like `expect(getCmds(reducer(state, action))).toContain(Cmd.run(someFunction))` where `getCmds` always returns an array whether the loop had a single `Cmd.run` or `Cmd.batch` or `Cmd.sequence` or just returned model state. Collections for the win! :) 

---

While these problems are kind of separate, I opened a single issue for them because I think the solution for one may inform the solution of the other. Overall, it'd be great to push forward a more concrete, supported testing strategy for `Cmd` objects, but feel free to split this up into separate issues as you see fit.

**Comment by bdwain** [comment]
Sorry for the delayed response. I think you're right though. We can definitely improve the testing API. In general though, I think it's best not to just add methods to Cmds that just return their internal data. I have some alternative ideas that I think solve the same problems without exposing the internals of the Cmds as much.

Number 2 is a simpler problem so I'll start with that one. I think rather than exposing the array, you can just make use of the array matchers that your testing framework exposes. For example, in jasmine, if you want to test that your `Cmd.batch` contains `Cmd.run(foo)`, you could say `expect(cmd).toEqual(Cmd.batch(jasmine. arrayContaining([Cmd.run(foo)])))` or something along those lines. There's [many others](https://jasmine.github.io/api/2.8/jasmine.html) that jasmine provides, and while I haven't used other testing frameworks, I think most of the common ones offer similar functionality. This would let us not change the API at all and create our test commands the same way we do our regular ones, while only providing the info we care about for that test.

I tried out arrayContaining and it almost worked. The one issue is that the the functions that create Cmds all have invariants like this

```js
  if (process.env.NODE_ENV !== 'production') {
    throwInvariant(
      Array.isArray(cmds) && cmds.every(isCmd),
      'Cmd.batch: first and only argument to Cmd.batch must be an array of other Cmds'
    )
  }
```

and the jasmine object is not an array. I think that could be solved by just adding an option to Cmd.batch and Cmd.sequence to skip the check. 


Issue 1 is more complicated. I think lots of libraries run into this issue and solve it just by ignoring functions when doing equality checks (i'm thinking of angular.equals and jasmine-expect-jsx), which I'd rather not do.

If possible I'd also like to avoid adding a method that just returns the action creator(s) to the user. I feel like it'd be preferable to have it run the action creator for you and have you compare the results instead of just returning a function to you. I'd also like to keep to have it still compare the functions in the cmds by default, because in most cases you are just using a plain action creator and that'll work.

In the case where you are creating your action creator at run time, I think it'd be best to just split the test into 2 parts: testing equality and verifying the resulting action. When testing equality, you could use `jasmine.any(Function)` or something similar when creating your Cmd to have it match the created action creators (this may need an option to disable the invariant also, like above).

To test the result, I think rather than have a `getSuccessActionCreator` method, it'd be preferable to have a method that simulates a success or failure and runs the result you give it through your action creator. Something like `expect(cmd.simulateSuccess(foo)).toEqual(getActionCreator(123)(foo))`. Those would only really be necessary on Cmd.run, though it might be helpful for all cmds to implement them so that you can test those types of actions even when they are nested under batches.

Thoughts?

**Comment by jon-thompson** [comment]
I agree with your thoughts on the action creator issue. Simulating success or failure (perhaps similar to how enzyme simulates events for React components) is probably a good approach to take that feels natural and familiar and can also be easily extended later if needed.

As for the batch issue, how about instead of using something like `jasmine.arrayContaining` we enhance `Cmd` objects to act like arrays, so that we can use a matcher like `toContain`. For example: `expect(cmd).toContain(Cmd.run(foo))`. If we could pull that off, I think it'd be 1) more explicit, 2) more readily usable for other frameworks, and 3) more compliant with the existing invariants.

**Comment by bdwain** [comment]
hm if we can pull that off then that would be cool. it might require something super hacky and hard to maintain though. I've been looking at how contains is implemented in jasmine vs chai and they both seem to just get your type as a string and if they don't recognize it, they go through custom logic to try to figure out if your object contains the thing you specified. It might be tough to maintain something that stays compatible with different matching libraries, and we'd always be tied to their implementation details.

One of the things I liked about jasmine.arrayContaining is that as long as your testing library has something like that implemented, it would work without any knowledge of how it works on our part.

One alternative idea i had is to add custom matchers for popular testing libraries that can work on Cmds and loops and stuff. I would want to make a separate project for them, like redux-loop-jasmine-matchers or something. But that would be another way of making it easy to compare things in tests without worrying about the implementation of the testing libraries.

**Comment by jon-thompson** [comment]
Yeah if that's the case, it does sound difficult to maintain.

I like the idea of creating matcher libraries; that's probably the ideal way to handle this. That might also be a lot to maintain though.

I think disabling or changing the invariants to allow `jasmine.arrayContaining` is probably the most practical compromise for now until there's more demand for other matchers. Personally, I'd prefer to see the invariants changed to accept a jasmine object instead of taking a flag to disable the invariants if that's possible without too much of a hassle. Being able to disable invariants feels wrong to me :)

**Comment by bdwain** [comment]
i'd rather not put jasmine specific stuff in the core library. But we could put a guard to make sure that the disable option is never used in production. or at least warn if it is (even though the the invariant does nothing in production anyway)

**Comment by gniquil** [comment]
@jon-thompson I had the exact same issue as you did in regards to 1). For me in your scenario, you can simply predefine an action creator function and your lifted state should be comparable as the predefined functions are stable (whereas anonymous functions are not)

However, this doesn't work if you have a scenario where your success|fail action creator needs more than the result|error as the argument. For example, if you fetch some data from the server based on some argument passed in the action (let's an object id). You can just naively modify the state once the promise resolves or rejects. However, some fetches may take longer than others to resolve. So you may run into concurrency issues as the resolved fetch may have originated from a different id. So in a way, I would like to pass additional arguments to my action creator:

```javascript
loop(
  newState,
  Cmd.run(
    fetchData,
    {
      args: [action.id],
      successActionCreator: (result) => didSucceed(action.id, result)
    }
  )
)
```
Now we are back to your original problem. The returned loop is no longer comparable as successActionCreator is always a new function. To get around it, somewhere in my code, I have:

```typescript
// in src/utils/functions.ts
type Partial = {
  (...args: any[]): any;
  original: {
    func: Function;
    args: any[];
  };
};

export function partial(func: Function, ...args: any[]): Partial {
  const partiallyApplied: any = (...finalArgs: any[]) => {
    return func.apply(null, [...args, ...finalArgs]);
  };
  partiallyApplied.original = { func, args };

  return partiallyApplied;
}
```
Now with that you can do the following:
```javascript
loop(
  newState,
  Cmd.run(
    fetchData,
    {
      args: [action.id],
      successActionCreator: partial(didSucceed, action.id)
    }
  )
)
```
Unlike normal partial from say Ramda though, you can compare an attribute of the partially applied function
```javascript
// assuming successActionCreator = partial(didSucceed, action.id)
assert(successActionCreator.original.func === didSucceed)
assert(successActionCreator.original.args[0] === action.id)
```
So with this you can define a custom `toEqual` to test loop equivalence. 

Note though, this gives me a bit of dirty feeling (type safety?). 

@bdwain I think perhaps as an enhancement, what we really want is change successActionCreator and failActionCreator to the following signature and have redux loop concat the final result to `partialArgs` and apply them when the command resolves/rejects.

```typescript
type PartialActionCreator<A> = {
  actionCreator: ActionCreator<A>;
  partialArgs: any[];
}

export interface RunCmd<A extends Action> {
  type: 'RUN';
  func: Function;
  options: {
    args: any[];
    failActionCreator: ActionCreator<A> | PartialActionCreator<A>;
    successActionCreator: ActionCreator<A> | PartialActionCreator<A>;
    forceSync: boolean;
  };
}
```

**Comment by gniquil** [comment]
Hi @bdwain @jon-thompson,

I just submitted a pull request #152. This should help address the first problem mentioned in the original issue.

Frank

**Comment by bdwain** [comment]
I'm going to mess around with the Cmd simulations and allowing jasmine matchers

**Comment by bdwain** [comment]
I'm gonna close this since I think the issues are addressed for now. Long term it'd be interesting to look into specific testing packages, but idk if that needs to be done yet.
