### ISSUE TITLE
Combined reducer is not compatible with redux `createStore`

### ISSUE THREAD

**Issue by gniquil** [redux-loop/redux-loop#147]
Thanks for the typescript support. Things worked like a charm except in the store setup. The following code

```javascript
const store = createStore(rootReducer, enhancer);
```
would cause typescript to complain about `Argument of type 'LiftedLoopReducer<...>' is not assignable to parameter of type 'Reducer<...>.'.`

Is there anything I can do here?

**Comment by willisplummer** [comment]
@jaredklewis Do you have any experience with this? i'm going to try to dig into it a little bit more tomorrow.

At work we do something like the followIng to overload redux's `StoreCreator` type so that `createStore` will support redux-loop's `EnhancedStore`:

`typings/redux/index.d.ts`:
```
import 'redux';

declare module 'redux' {
  export interface StoreCreator {
    <S, T>(reducer: EnhancedReducer<S, T>, preloadedState: S, enhancer: StoreEnhancer<S>): Store<S>;
  }
  interface EnhancedReducer<S, T> {
    <A extends Action>(state: S, action: A): T;
  }
}
```

**Comment by willisplummer** [comment]
@gniquil this is kind of a hack but it works(?)

```
import { createStore } from "redux";
import { install, LoopReducer, StoreCreator } from "../../index";

type CounterState = number;

type CounterActions = {
  type: "INCREMENT";
};

const counterReducer: LoopReducer<CounterState, CounterActions> = (
  state: CounterState,
  action: CounterActions
): CounterState => {
  switch (action.type) {
    case "INCREMENT":
      return state + 1;
    default:
      return state;
  }
};

const enhancedCreateStore = createStore as StoreCreator;

const store = enhancedCreateStore(counterReducer, 0, install());
```

**Comment by jaredklewis** [comment]
Hello. For the time being, I think the best "solution" is just to cast the `LoopReducer` to an `any` to get things working.

```typescript
import reducer from "..."; // assuming this is a LoopReducer
const store: Store<AppStore> = createStore<AppStore>(reducer as any, install());
```

Unless the upstream `redux` project wants to make their `createStore` or `Reducer` types more generic, I can't think of anyway this can work out of the box.

I guess `redux-loop` could expose a simple `createStore` wrapper that is just the redux project's version with a new method signature.

```typescript
// in js land
import {createStore} from "redux"
export createStore;

// index.d.ts
declare function createStore<S, A>(reducer: Reducer<S> | LoopReducer<S, A>, enhancer: StoreEnhancer<S>): Store<S>;
```

**Comment by willisplummer** [comment]
I think that the _solution_ of casting alongside adding some documentation to the ReadMe feels like the best approach. @bdwain what do you think?

**Comment by gniquil** [comment]
This is exactly what I’m doing. But my project created from CRA with
react-scripts-to always shows warnings about casting to any.

**Comment by willisplummer** [comment]
@gniquil can you just disable the warning in this case? alternatively, does casting `createStore` as redux-loop's `StoreCreator` type resolve the issue for you?

**Comment by gniquil** [comment]
@willisplummer I will cast to `any` for now. 

But I think the better approach would be to provide a different `createStore` with a different signature. The warning (or error without casting) is actually correct in that the normal `createStore` does not and should not take a `LiftedReducer` as an argument, without having `install`ing a special enhancer. And from another perspective, perhaps it's the `install` enhancer that's the problem? 

Overall perhaps we could retool the enhancer piece to make it easier to integrate redux-loop. I've worked with redux-loop on 2 projects, both of which have a tons of enhancers/middlewares. And I remember finding the position of `install` has always been a big issue with this project. Currently I'm using it with redux-first-router. I spent hours debugging issues caused by this. 

So one random thought (as a 5.0 suggestion), why don't we stick the commands into the state? I know this sounds crazy and is diverging from Elm. But conceptually:

1. since commands are just description of side effects, and description is just data, it is not too different (conceptually) from state (imagine state having a key `commands`
2. to run the commands, at every tick, redux-loop runtime just looks at the commands state, runs them, and clears them
For example:
```javascript
const reducer = (state, action) => {
  switch (action.type) {
    case 'FIRE_MISSILE':
    return {
      ...state,
      missileFired: state.missileFired + 1,
      [Cmd.key]: [
        Cmd.run(fireMissile, { successActionCreator: evilLaugh }),
        ...state[Cmd.key]
      ]
    }
    ...
  }
}
```
So at every tick, redux-loop would inspect the entire state and gather all parts with key `Cmd.key` (some symbol or magic string).

And here are the benefits:

1. simple integration with any redux devtools
2. we get back to a "normal" reducer, and the enhancer doesn't have to do super tricky things.

**Comment by bdwain** [comment]
@gniquil I'm not sure that storing Cmds in state would work well because Cmds contain functions and so can't be serialized. A lot of redux tools are built around the serialization of the state and  those would break. See http://redux.js.org/docs/faq/OrganizingState.html#can-i-put-functions-promises-or-other-non-serializable-items-in-my-store-state. 

I do agree that figuring out the right order for middleware/enhancers is a hard problem and I think we could do a better job documenting tips on it specific to redux loop. Unfortunately I think it's actually a limitation of the design of redux and there's not something specific we could do to fix it as redux loop. The middlewares/enhancers are all composed and run in a certain order and most middlewares do significant enough things that the order matters (like if you had a dependency injection middleware and a logger middleware, you'd want to log actions after they ran through the DI), but it's impossible to predict what the order should be in every scenario without knowing which middlewares will be used ahead of time.

As far as the issue at hand, I think since we need to call vanilla redux's createStore at some point, there's no way around casting it at some point. But we could expose a version of createStore that does that for you if you use typescript, but does nothing else. And you would only need to use it if you used typescript. One of the ideas I mentioned in #133 was to make more libraries with tools for using redux-loop with specific libraries (like immutablejs, typescript, different testing libraries, etc...). So you could maybe install redux-loop-typescript which would use vanilla redux loop under the hood but have the typings and things like this casting createStore.

**Comment by jaredklewis** [comment]
@bdwain 

I am not sure I understand correctly, but don't we already put commands in the store anyway? redux-loop considers the first element of the array to be the "Store" and the second to be a Command, but this is just the way redux-loop thinks about the data structure. From the perspective of redux (and other redux middleware), until redux-loop strips out the command part, the containing array IS the store.

A little off topic, but what kinds of redux middleware break if redux-loop is the first middleware? It seems like it would be ideal that redux-loop goes first, strips out the commands, and then everything goes on it's way, but it seems from the comments most people have to situate it some magical position in the middle?

**Comment by bdwain** [comment]
We don't store commands. Inside install.js you can see this snippet of code 

'''js
    const liftReducer = (reducer) => (state, action) => {
      const result = reducer(state, action)
      const [model, cmd] = liftState(result)
      cmdsQueue.push({ originalAction: action, cmd })
      return model
'''

We take the return value, break out the cmds and push them into a queue and then return only the model to the plain redux store which lives inside of the loop code. 

Once dispatch is done we run the cmds in the queue. 

As far as things that break. I don't think it's really middleware that's the issue. It's anytning that relies on replaying actions or serializing the state. For example time travel debugging in devtools.

**Comment by jaredklewis** [comment]
Right, so I think I follow this part. My understanding of @gniquil 's idea is that it also does not store the command in the model long term, just as temporary holding place (same as last element of array in the current implementation).

```typescript
// Current implementation:
// when state comes in, it has a command (or we add it with lift state): [Model, Cmd]
const liftReducer: LiftReducer = (reducer) => (state, action) => {
      const result = reducer(state, action)
      const [model, cmd] = liftState(result)
      cmdsQueue.push({ originalAction: action, cmd })
      return model // when state goes out, it is only Model
}

// Proposed implementation:
// when state comes in, it is Model with maybe an extra key [Cmd.key] with a command
const liftReducer: LiftReducer = (reducer) => (state, action) => {
      const result = reducer(state, action)
      const cmd = state[Cmd.key] || Cmd.none
      state[Cmd.key] = undefined
      cmdsQueue.push({ originalAction: action, cmd })
      return state // when the Model goes out, it is a pure model with no commands
}

// The second implementation supports the redux createStore method without casting to typescript.
// It also eliminates the need for a special combine reducers function or special `LoopReducer` type

// The Loop type signature becomes this. Behind the scenes we are actually returning
// S & { [Cmd.key]: Cmd<A> }, but there is no reason to expose that, as the command key
// is only for internal use by redux-loop
declare function loop<S>(state: S, loop: CmdType<A>): S;

// Now we can use createStore as normal
interface AppStore  {
    // no commands show up here
    foo: string; 
}

const reducer: Reducer<AppStore> = (state, action) => {
    switch (action.type) {
        case "INIT":
            return loop(state, Cmd.run(action.thingy, { ... }))

        case "OTHER":
            return Object.assign({}, state, { foo: "bar" })
    }
};
const appStore = createStore<AppStore>(reducer, install())

// this compiles using the default Redux types, sans-casting
```
Though not shown above, obviously this idea requires changing the `loop` function to add in command keys rather than putting the model into an array with the command.

Whether all of this change would be worth the benefits (no need for special `combineReducers`, no need to cast `createStore in typescript), I'm not sure 😄 .

**Comment by bdwain** [comment]
I still think we'd need a special combineReducers. Otherwise, our state shape might look like this

```js
[
  {
    foo: [fooState, cmd],
    bar: [barState, cmd]
  },
  toplevelCmd
]
```

and any futrther nesting would be reflected inside of fooState and barState.

combineReducers batches up all of the cmds of the children into a single command and merges the children state into a single parent state. I think we still need that functionality at every nesting level in the state tree.

**Comment by jaredklewis** [comment]
Good point.  

I was thinking `loop` never returns an array (always returns an object), so the state shape would always just be the shape it is normally with `Cmd.key` properties scattered around.
In that case, to avoid a custom combineReducers, they could be batched in liftReducer:

```js
const liftReducer: LiftReducer = (reducer) => (state, action) => {
      const result = reducer(state, action)
      const cmds = findNodes(state) // findNodes recursively searches tree Cmd.key props, returns as array
      const cmd = cmds.length > 1 ? Cmd.batch(cmds) : cmds[0]; 
      state[Cmd.key] = undefined
      cmdsQueue.push({ originalAction: action, cmd })
      return state
}
```

Though this I imagine is less performant than batching inside `combineReducers`. So maybe better to keep combineReducers. Just thinking out loud 😄

**Comment by bdwain** [comment]
It's an interesting idea. Getting rid of combine reducers would be great. But yea I think doing a deep traversal of the tree every action would be bad for performance.

**Comment by gniquil** [comment]
What if we implement a very simple dirty checking flag? I.e every time you call Cmd.run/action/list we dirty a flag and clear it after running the side effects. This avoid traversing the tree every time. Feels hacky but should work.

**Comment by bdwain** [comment]
It could get really slow if you have a large state tree or large objects in the state tree. In general I'd be hesitant of anything that had performance scale with the size of the state tree.

**Comment by bdwain** [comment]
Can this issue be closed or is there still a bug to address?

**Comment by jaredklewis** [comment]
Not the OP, but I think #160 will basically resolve this, as the plan at least for now seems to be casting.

**Comment by bdwain** [comment]
ok i'll close this in favor of #160
