### ISSUE TITLE
Slack channel

### ISSUE THREAD

**Issue by ashishsc** [redux-loop/redux-loop#161]
Might be good for the community to have a redux-loop slack channel /discord /gitter (or a sub-channel under redux)

**Comment by bdwain** [comment]
yea that would be awesome! I think a sub channel under redux makes sense. Reactiflux right?

**Comment by bdwain** [comment]
sounds like they're hesitant to make new channels for a single library right now without a lot of chatter already. They suggested directing traffic to the redux channel, but i don't really want to do that because there's so much else going on that it's hard to monitor for redux loop specific stuff. 

I'm hoping they change their mind, but if not, they said they are probably going to start having channel groups soon, at which point they'd be more open to the idea. So I think our options are (assuming they won't give us a channel now) wait for them to give us a channel or just use gitter. 

I think it'd be good for more redux and react related topics to be in reactiflux and not fragmented all over, so I'd rather not use gitter if possible, but I also don't want to wait too long or have to switch channels once they actually let us (i've also seen them say they won't make a channel if there's a gitter channel also).

**Comment by ashishsc** [comment]
I see, that's a shame. Loop is pretty popular though, so I'm sure that the sooner we get something up the better. ![Loop Stats](https://i.imgur.com/kyTvzLg.png)

**Comment by willisplummer** [comment]
We could set up a redux-loop specific free-tier slack channel in the short-term? Wouldn't hurt to just migrate to redux later if they let us but i think having a hub for conversation would be a great way to encourage more people to get involved with the project

**Comment by bdwain** [comment]
yea i think that makes sense. Reactiflux is dragging their feet on allowing new channels and I don't want to wait forever. I use slack for work and like it and would obviously be happy to have a single app. Does anyone have any experience with gitter? It sounds like the other main alternative and I'm just curious if there's any reason it would be better. Otherwise I think more people are already using slack anyway.

**Comment by bdwain** [comment]
Ok I made a slack channel. I invited both of you. Is there any reason I shouldn't just post an invite link on the front page? I haven't deal with public channels much before. Looks like we'd have to change the invite link every 30 days, which is annoying. I was looking at some other public channels and they all have signup pages where you have to enter a url, but that seems annoying.

**Comment by bdwain** [comment]
oh cool i guess there's https://github.com/rauchg/slackin

**Comment by bdwain** [comment]
https://reduxloop-slack.herokuapp.com/

i had to make some random gmail account to send the invites from, which is a little weird, but it works.

<img width="701" alt="screen shot 2017-10-13 at 12 48 10 am" src="https://user-images.githubusercontent.com/3982094/31532006-4e1e5bbc-afb0-11e7-8de5-b85f4a21a39b.png">
