### ISSUE TITLE
[BUG] Cmd.map(Cmd.list(...)) is broken

### ISSUE THREAD

**Issue by gniquil** [redux-loop/redux-loop#162]
If a "subreducer" returns a list of cmds. Cmd.map does not do the right thing by mapping the high order action creator over each cmd's success/fail action creators in the list.

**Comment by gniquil** [comment]
Not sure if this is the root cause, but here, in the `cmd.js` file:

```js
function handleParallelList({cmds, batch = false}, dispatch, getState){
  const promises = cmds.map(nestedCmd => {
    const possiblePromise = executeCmd(nestedCmd, dispatch, getState);
    if(!possiblePromise || batch){
      return possiblePromise;
    }

    return possiblePromise.then(result => {
// HERE-------------------------------|
      return Promise.all(result.map(a => dispatch(a)));
    });
  }).filter(x => x);

  if (promises.length === 0){
    return null;
  }

  return Promise.all(promises).then(flatten).then(actions => {
    return batch ? actions : [];
  });
}
```
Is this dispatch action directly? Shouldn't these functions return some type of array of actions, and then have Cmd.map potentially wrap the actions and wait for the dispatch? Not sure how this will play with async/batch settings.

Frank

**Comment by gniquil** [comment]
Just tried a few things. It seems with `batch: true`, `map` with `list` works

**Comment by bdwain** [comment]
Hi @gniquil. Sorry I maybe could have made this warning more prominent. In the notes section for Cmd.map's documentation it mentions. 

>If you want to map a nested list Cmd, it's important to enable the batch option on the list. Otherwise, the list does not return any of the dispatched actions as they are all dispatched while running the list Cmd.

I don't think there would be a good way around this because the whole idea behind turning batch mode off is that the actions are dispatched as soon as they are ready and there is no single "batch" returned through a promise.

**Comment by gniquil** [comment]
Ok, sorry missed that note. Would it be a better idea to set batch to true by default? I am not sure how everyone else is using the library. But for us, we are using it the way it's used in Elm, i.e. decomposing reducers and forwarding actions to subreducers. In that case `list` is mostly used to combine commands, which would make more sense to do batch.

**Comment by bdwain** [comment]
I think in general we want batching off because it just delays results that are otherwise ready, which causes worse perceived performance. The only reason I can see to turn on batching is to make Cmd.map work.

I think we need to look at Cmd.map more in the future. I understand why it works the way it does in elm, but the concept of middleware makes it harder to use in redux. If you wrap an action, middleware will never see it, which would be a a really easy unexpected bug to cause. I have a pretty large app using redux loop and have never used it. 

I don't want to drop support for it, but idk if we can optimize for it as much just because of the differences between redux and elm.

**Comment by bdwain** [comment]
I think we could probably add a warning to Cmd.map to detect if the subcmd is an unbatched list. Would that be enough to replace the default being false?

**Comment by gniquil** [comment]
@bdwain I think for now a warning should probably do the trick.

As for support for `map`, please don't ever drop it. :) We rely so heavily on this it's not even funny. We use typescript at work. In order to get the types work smoothly, it's much better to adopt the elm style's decomposition. In addition, we are also working on a largish app (we had more than 300 actions) and thus could not scale the application correctly with too flat of a structure. The Elm way of decomposing into subreducers allows to reason about thing much more locally while giving us a lot of type safety. `map` is a key piece of this.

Nevertheless, thanks for lib though. We love this lib so much more than saga/observable/thunk. It's brilliant.

**Comment by bdwain** [comment]
Glad you enjoy it! @lukewestby is the one who deserves your thanks as he wrote it. I'm just trying to make sure it stays awesome.

As for Cmd.map, don't worry I wouldn't remove it. I would like to find a way to feature it more if possible and make it easier to understand, but the problem is getting around the middleware issue. Do you just not have any middleware that needs to see every action? 

I feel like in the app I work on we just couldn't use it because we rely heavily on this [dependency injection middleware](https://github.com/bdwain/redux-action-enhancer) I wrote that adds properties to actions automatically. We really only use combineReducers and mergeChildReducers to nest reducers.

**Comment by gniquil** [comment]
@bdwain I have an idea after looking through the code. If we don't want to break the api, what about this:

```js
Cmd.tag = (tagger, nestedCmd, ...args) => {
  switch(nestedCmd.type) {
    case cmdTypes.NONE:
      return nestedCmd;
    case cmdTypes.MAP: // once we deprecate `map` we can get rid of this
      return {
        ...nestedCmd,
        tagger: compose(tagger, nestedCmd.tagger)
      }
    case cmdTypes.LIST:
      return {
        ...nestedCmd,
        cmds: cmds.map(cmd => Cmd.tag(tagger, cmd, ...args))
      }
    case cmdTypes.ACTION:
      return {
        ...nestedCmd,
        actionToDispatch: tagger(actionToDispatch, ...args)
      }
    case cmdTypes.RUN:
      return {
        ...nestedCmd,
        options: {
           ...nestedCmd.options,
           successActionCreator: nestedCmd.options.successActionCreator 
             ? tagger(nestedCmd.options.successActionCreator, ...args) 
             : undefined,
           failActionCreator: nestedCmd.options.failActionCreator 
             ? tagger(nestedCmd.options.failActionCreator, ...args) 
             : undefined,
        }
     }
     default: // no need if we typescript/flow :)
       return nestedCmd;
   }
}

```

The main difference between `tag` and `map` is that tag is eager. When called, it eagerly produces a tagged version of the `nestedCmd`. That way, by the time you get to `executeCmd`, taggers have already been applied. Eventually, we could deprecate `map` as it is then completely redundant.

What do you think?

**Comment by bdwain** [comment]
I'm a little confused. I'm not sure what you mean by "taggers have already been applied". Can you provide an example of where this would be better? 

Also it looks like the run example is passing an action creator through tagger, not an action itself. Is that intentional? Seems like it'd be different from the current API

**Comment by gniquil** [comment]
@bdwain Sorry, my bad, on the `RUN` example. Here's a correction without thinking too much about it:

```js
Cmd.tag = (tagger, nestedCmd, ...args) => {
  switch(nestedCmd.type) {
    case cmdTypes.NONE:
      return nestedCmd;
    case cmdTypes.MAP:
      return {
        ...nestedCmd,
        tagger: (a) => tagger(nestedCmd.tagger(a, ...nestedCmd.args), ...args)
      }
    case cmdTypes.LIST:
      return {
        ...nestedCmd,
        cmds: cmds.map(cmd => Cmd.tag(tagger, cmd, ...args)) // recursively call `tag` again
      }
    case cmdTypes.ACTION:
      return {
        ...nestedCmd,
        actionToDispatch: tagger(actionToDispatch, ...args)
      }
    case cmdTypes.RUN:
      return {
        ...nestedCmd,
        options: {
           ...nestedCmd.options,
           successActionCreator: nestedCmd.options.successActionCreator 
             ? (a) => tagger(nestedCmd.options.successActionCreator(a), ...args)
             : undefined,
           failActionCreator: nestedCmd.options.failActionCreator 
             ? (a) => tagger(nestedCmd.options.failActionCreator(a), ...args)
             : undefined,
        }
     }
     default: // no need if we typescript/flow :)
       return nestedCmd;
   }
}
```

`Cmd.tag` should be used exactly like `Cmd.map`. 

The point is `Cmd.map` creates an intermediate data structure and it doesn't do anything until the redux-loop runtime starts executing the commands. `tag` however, reaches into the other commands and "compose wrap" the action creators immediately.

So for the `list` case, even if you set `batch: false`, and the runtime executes and immediately dispatches the success/fail action creators, these action creators have already been wrapped in tagger.

Is this clearer?

**Comment by bdwain** [comment]
Ah i see. That does make a bit more sense. So besides the unbatched lists this should not cause any difference in behavior right? If that's the case, that would be cool. and we could probably just keep it as Cmd.map then, but do it on a major version bump to be safe.

One issue with this though is that this isn't testable with an equality check because the action creators are created inline. Not sure if there's a way around that. I don't love the idea of not being able to say `expect(cmd).toEqual(....)` by default.  I know we can simulate cmds now, but i'd rather that be the exception.

**Comment by gniquil** [comment]
Haha you had me convinced with the simulate solution. To be perfectly honest I do agree if everything is just value, it would be so much better. This is actually why I originally proposed  allowing extra args for success and fail action creators. 

Back to the issue at hand. I think if we want to preserve map, we could add an extra “pass” before execution (I think it’s where queue.map(runCmd) in install.js). In this pass, we traverse the nested command tree and apply map. That should work right?

**Comment by bdwain** [comment]
maybe we could just simplify it to say

```js
Cmd.map = function(...){
...
  if(nestedCmd.type === cmdTypes.LIST && !nestedCmd.batch){
    nestedCmd.cmds = nestedCmd.cmds.map(cmd => Cmd.map(tagger, cmd, ...args));
  }
...
}
```

thoughts? That should limit the change to only the case where it matters. And not mess up any testing.

**Comment by bdwain** [comment]
Hm not sure what you mean in your last comment. Is it necessary if we do the thing I just suggested? How would the extra pass look?

**Comment by gniquil** [comment]
Here

```js
   const runCmds = (queue) => {
----------------------------------|
      const promises = queue.map(applyCmdMap).map(runCmd).filter((x) => x)
// or queue.map(compose(runCmd, applyCmdMap)).filter(...)
      if (promises.length === 0) {
        return Promise.resolve()
      } else if (promises.length === 1) {
        return promises[0]
      } else {
        return Promise.all(promises).then(() => {})
      }
    }
```

Here's an implementation of `applyCmdMap`:

```js
// assuming `Cmd.tag` as defined before
const applyCmdMap = (cmd) => {
  switch(cmd.type) {
    case cmdTypes.MAP: {
      const {tagger, nestedCmd, args} = cmd
      return Cmd.tag(tagger, applyCmdMap(nestedCmd), ...args) // this essentially removes the MAP command type
    }
    case cmdTypes.LIST: {
      const { cmds } = cmd
      return {
        ...cmd,
        cmds: cmds.map(applyCmdMap)
      }
    }
    case cmdTypes.NONE:
    case cmdTypes.ACTION:
    case cmdTypes.RUN:
    default:
       return cmd;
   }
}
```
Think of `applyCmdMap` as "withMapCmdAppliedAndRemoved". 

As for your solution above, if you modify `map`, what do you return though? If you had eagerly applied tagger, then would you return just the subcommand (i.e. the underlying List) or the "MAP" command but `tagger` substituted with an identity function? 

Personally I think, the best approach is inserting the extra `applyCmdMap`. It maintains existing API, but make it more "correct". I don't like the partial/targeted fix as special cases often lead to problems later. As for people who have to use it now (like me), I will just make it a helper in my app's utils file for now.

**Comment by bdwain** [comment]
sorry my example was just doing what yours did, but only when nestedCmd is list, instead of adding behavior for ALL cmds or doing. It's just adding some logic to the Cmd.map method (which creates map cmds).

```js
const map = (
  nestedCmd,
  tagger,
  ...args
) => {
 //invariants removed to make it shorter

  //this if is the only new thing i think we need
  if(nestedCmd.type === cmdTypes.LIST && !nestedCmd.batch){
    nestedCmd.cmds = nestedCmd.cmds.map(cmd => Cmd.map(tagger, cmd, ...args));
  }

  return Object.freeze({
    [isCmdSymbol]: true,
    type: cmdTypes.MAP,
    tagger,
    nestedCmd,
    args,
    simulate: simulateMap
  });
}
```

it's basically just like cmd.tag. but we don't need special case logic for the other cmd types because it wouldn't make a difference anyway. unbatched lists under maps are the only things where it matters.

**Comment by gniquil** [comment]
@bdwain I think the special case I am thinking about is for future development. This special case is coupled to the specific implementation of the map + list behavior right now. It could make the code complex later.

What do you think about the apply map idea. It doesn't change the API, makes it more correct, and still maintains testability (as much as we have today at least).

**Comment by bdwain** [comment]
Doesn't the apply map idea depend on Cmd.tag though, which is what breaks the testability in the first place?

**Comment by gniquil** [comment]
Sorry I wasn’t clear. With applyCmdMap we don’t expose tag function anymore. So there will be zero change in API.

**Comment by bdwain** [comment]
but then what does it do to map cmds? you had it as 

```js
// assuming `Cmd.tag` as defined before
const applyCmdMap = (cmd) => {
  switch(cmd.type) {
    case cmdTypes.MAP: {
      const {tagger, nestedCmd, args} = cmd
      return Cmd.tag(tagger, applyCmdMap(nestedCmd), ...args) // this essentially removes the MAP command type
```

**Comment by gniquil** [comment]
So right before we execute each command in the queue, we apply the tagger to the nested commands recursively. So when the actual execution begin, nested command will contain no `MAP` structure anymore.

**Comment by bdwain** [comment]
I think that since we need to do it before we execute the Cmd, we could do it on creation of the cmd rather than before execution. That'd be simpler and we could avoid having to change install.js.

If we changed Cmds to be a class with inheritance it would be pretty simple to just have some method on a Cmd like mapify or something and the default behavior would be to do nothing but for lists and maps we could put specific logic in there.

I do think we want to avoid wrapping the list's Cmds in map if it is batched because otherwise they will be rewrapped. But that logic could be contained within the ListCmd class or something.
