### ISSUE TITLE
Make this more extensible by providing a customizable "runtime"

### ISSUE THREAD

**Issue by gniquil** [redux-loop/redux-loop#164]
Currently, the execution logic is all encapsulated in `install.js`. Mostly, there is a private var `cmdsQueue` and the execution is hard coded in the install function that it can't be changed. I think we can extract this into a more customizable runtime object to achieve following benefits:

1. customize the runtime behavior #162
2. helps tooling #131 (monitors can get a look at the commands queue)

Here's how the `install` function would look with such a runtime:

```js
export function install(runtime) {
  if (!runtime) { // user can provide an alternate runtime
    runtime = new Runtime();
  }

  // note this returns the runtime and the store enhancer
  return [
    runtime,
    next => (reducer, initialState, enhancer) => {
      const [initialModel, initialCmd] = runtime.liftState(initialState);

      const store = next(runtime.liftReducer(reducer), initialModel, enhancer);

      const dispatch = action => {
        store.dispatch(action);
        return runtime.runCmds(runtime.dequeueAll())
      };

      const replaceReducer = reducer => {
        return store.replaceReducer(runtime.liftReducer(reducer));
      };

      runtime.runCmd({
        originalAction: { type: '@@ReduxLoop/INIT' },
        cmd: initialCmd,
      });

      return {
        ...store,
        dispatch,
        replaceReducer,
      };
    },
  ];
}

```

The Runtime would have the following API. We can now just use standard class inheritance to customize the behavior (why OO?, queue is stateful, this is more natural?) The `Runtime` API will certainly be for advanced usage. But people wouldn't even know if they don't bother (completely compatible with existing API). 

```js
class Runtime {
  queue: Queue // queue of Items, type Item = { originalAction: Action, cmd: CmdType<Any> }
  enqueue: (item) => void // 
  dequeueAll: () => Queue // return and reset the internal queue

  liftState: (state) => [State, CmdType<Any>]
  liftReducer: (reducer) => LiftedReducer // important thing here is to add enqueue to reducer 

  runCmds: (queue) => Promise<?> // run the queue of command
  runCmd: ({ originalAction, cmd }) => Promise<CmdType>
}
```

Here's the straight forward implementation: 

```js

class Runtime {
  // type Item = { originalAction: action, cmd },
  queue: []; // queue: Item[]

  liftState: liftState // imported from './loop'

  liftReducer(reducer) {
    return (state, action) => {
      const result = reducer(state, action);
      const [model, cmd] = this.liftState(result);
      this.enqueue({ originalAction: action, cmd });
      return model;
    }
  }

  enqueue(item) {
    this.queue.push(item)
  }

  dequeueAll() {
    const runningQueue = this.queue;
    this.queue = []
    return runningQueue
  }

  runCmds(queue) {
    const promises = queue.map(runCmd).filter(x => x);
    if (promises.length === 0) {
      return Promise.resolve();
    } else if (promises.length === 1) {
      return promises[0];
    } else {
      return Promise.all(promises).then(() => {});
    }
  };

  runCmd({ originalAction, cmd }) {
    const cmdPromise = executeCmd(cmd, dispatch, store.getState);

    if (!cmdPromise) return null;

    return cmdPromise
      .then(actions => {
        if (!actions.length) return;
        return Promise.all(actions.map(dispatch));
      })
      .catch(error => {
        console.error(loopPromiseCaughtError(originalAction.type, error));
        throw error;
      });
  }
}
```

**Comment by lsunsi** [comment]
This is a cool idea. So cool that I'd be willing to code something like that from scratch. (: Just a +1

**Comment by bdwain** [comment]
Sorry I never got around to responding to this. I haven't had a ton of time the last few weeks.

I agree it's a cool idea and would make things like devtools much easier to implement. If you want to make a PR for it that would be awesome. If not I can try to do it at some point.

**Comment by lukewestby** [comment]
hey there folks

i'm luke, i wrote the first couple versions of this library way long ago in javascript years. i just popped in to see how things were going and this issue caught my attention so i wanted to leave some thoughts.

1. "customize the runtime behavior" is sort of a restatement of what the feature request is and so probably not a sufficient justification for building it. if the linked issue on that line is a really bug then the move would be to fix the bug. if the scheduler or api need to be improved then i would think improving them in place would be of greater benefit to all of the library's users than allowing certain advanced users to go roll their own on an ad-hoc basis. this is a really big thing to expose and i'd be willing to bet you'll get plenty of "what's this?" type questions for doing it. at the very least, you might consider exposing the particular customizations you need as configuration rather than making it possible to pass an entire scheduler implementation.

2. if you're following me on (1), the scope of this change is larger than it needs to be in order to do what essentially amounts to providing redux devtools access to the queue of pending commands. the suggestions that @gniquil provided in that issue look like they work pretty well already.

just as a general reminder as well: everything a library doesn't hide from the user needs to be understood by the user at some level. making the runtime an optional argument means you need to document that argument. then you need to document the entire runtime class, and probably write a tutorial on how to make one if more users than those who designed the feature are to get the benefit of the option. one of the cool things about this library is that you just return some data from your reducer and then your effects run and give you some results and you don't have to concern yourself with how that happens.

anyway, these are just observations and if you feel like i'm not seeing the whole picture on this then don't pay me any mind 😊

**Comment by bdwain** [comment]
thanks @lukewestby those are good points. The customizable runtime is probably getting too far ahead of ourselves. Eventually it may be the only reasonable solution if we want to support a variety of integrations with other libraries, but right now I agree that redux devtools is not enough of a reason on its own to do that.

**Comment by bdwain** [comment]
Gonna close this for now since #131 is already open.
