### ISSUE TITLE
Redux-persist new API is incompatible with redux-loop

### ISSUE THREAD

**Issue by lsunsi** [redux-loop/redux-loop#166]
Related issue: https://github.com/rt2zz/redux-persist/issues/501

I'd like to discuss what's the best option for fixing this, since these two packages are awesome and I think I'm not the only one that'll want to use them together.

Their new API relies on the proper reducer signature, that's why it's incompatible.

**Comment by bdwain** [comment]
I'm not too familiar with redux-persist, but it seems like the new version needs to change the top level reducer signature? I don't think there's a good way to make redux-loop work without returning a loop object from the top reducer instead of the actual state (though if there is I'd be interested). 

It may be possible to write a store enhancer that lives between redux-loop and redux-persist and makes their API's compatible, but I'd need to look more into it to be sure.

**Comment by lsunsi** [comment]
@bdwain I think the first point of incompatibility is that it expects the reducer to always return an object, no matter what. If you'd ask me, I'd say it's a little unelegant.

**Comment by bdwain** [comment]
Oh yeah that would break if your root state is an array and you used no other middleware. It could definitely be more flexible.

**Comment by johhansantana** [comment]
I commented on the other issue mentioned here but just in case. Any way to make this work? Using a default state as an array seems to break it.

**Comment by bdwain** [comment]
i can comment on that issue

**Comment by azai91** [comment]
any way to make these libraries compatible?

**Comment by bdwain** [comment]
nothing has changed on redux loop's end. I think any change to make these compatible would need to happen outside of redux loop. I mentioned suggestions on what to do in https://github.com/rt2zz/redux-persist/issues/501, but im not an expert on redux-persist, so i can't say if they are right or make them happen. it's also been 5 years so i don't know what has changed
