### ISSUE TITLE
[Question]: How would I implement a request queue

### ISSUE THREAD

**Issue by on3iro** [redux-loop/redux-loop#176]
Hey, 

I am currently having a rather specific problem that I am not quite sure of how I should tackle it.
I am building some kind of task board and whenever a task is dragged around, I will immediately update the store and run a command to initiate a server request. If the request is unsuccessful the old state will be restored.
However because of the asynchrounous nature of these sideeffects it might be, that two tasks fail in quick succession, and the second tasks old-state will overwrite the first tasks old state, which leads to an overall wrong application state. 

Now I am trying to think of a way to queue my sideffects. So that these specific requests do not run simultaneously and are instead handled one after another.
Is there a recommended way of how to approach a problem like this with redux-loop?

Thanks in advance!

**Comment by bdwain** [comment]
Hi @on3iro . I'm assuming that these side effects are triggered independently. One event does not trigger 2 side effects, right? Because in that case, you could just use [Cmd.list](https://redux-loop.js.org/docs/api-docs/cmds.html#cmdlistcmds-options) with the sequence option.

Assuming that the side effects are triggered independently, I think you actually said the answer already. You want to queue them up, which is something that can be represented in your application's state. 

For example, let's say you dispatch 2 events in quick succession, one saying that item 123 was dragged, and one saying item 456 was dragged. There would be an ITEM_MOVED action, a REQUEST_SUCCESS action, and a REQUEST_FAILED action to handle. 

On ITEM_MOVED, you'd either start a request or add it to the back of the queue, depending on if there are items in the queue already. On REQUEST_SUCCESS, you'd remove the old request off of the front of the queue and start the next one (if there was a next one). On REQUEST_FAILED, you'd throw away the rest of the queue (or you could continue on in a different way if you wanted to).

Here's how you could handle those 3 types of actions

```js
const initialState = {
   queue: [],
   error: false,
   //other fields
};

function handleItemMovedAction(state, action){
  let queue = state.queue;
  if(queue.length){ //something is already running so just add a request to the queue
    return {
      ...state,
      queue: queue.concat([action.id]) //add new request to back of queu
    };
  }
  //nothing is running so just add the new request to the front of the queue and run it
  let newState = {
    ...state,
    queue: [action.id]
  };
  return loop(newState, Cmd.run(doRequest, {
    args: [action.id],
    successActionCreator: requestSuccessAction,
    failActionCreator: requestFailAction
  }));
}

function handleRequestSuccessAction(state, action){
  let newState = {
    ...state,
    queue: state.queue.slice(1) //remove old request from front of queue
  };
  if(!newState.queue.length){
    //no more requests in the queue
    return newState;
  }
  //start the next request
  return loop(newState, Cmd.run(doRequest, {
    args: [newState.queue[0]],
    successActionCreator: requestSuccessAction,
    failActionCreator: requestFailAction
  }));
}

function handleRequestFailedAction(state, action){
  return {
    ...state,
    queue: [], //clear queue on failure
    error: true
  }
}
```

**Comment by on3iro** [comment]
@bdwain Thanks for the detailed answer! This is super helpful. I hope I'll find an opportunity to contribute to this awesome library in the future and return the favor ;)

**Comment by bdwain** [comment]
glad I could help!
