### ISSUE TITLE
Custom command types

### ISSUE THREAD

**Issue by jonaskello** [redux-loop/redux-loop#186]
I just started using redux-loop, been going quite good so far. I started out by using `Cmd.run` and declaring the functions that contain the side-effects in my reducers. However I soon felt that I would like the definition of the commands to be more decoupled from the execution of the commands. Basically I would like to think of my commands in the same terms as actions. So a command would just be a data record with a type and a payload (analog to an action). Then I would like to provide an executer with a switch statement on type (analog to a reducer).

Currently if the command type is unknown an error is thrown [here](https://github.com/redux-loop/redux-loop/blob/master/src/cmd.js#L130). I was thinking instead when install is called we can pass in an executor function which in called in this case. So something like this:

```js
// Define executor function somewhere
function executor(cmd, dispatch, getState) {
  switch(cmd.type) {
     case "mycommand1":
       // Do side effect
       // Dispatch complete action
  }
}

// Pass executor function to install, when a command unknown to redux-loop appears the executor function is called
const store = createStore(reducer, initialState, install(executor));

// In the reducer
function reducer(state = initialState, action) {
  switch(action.type) {
  case 'FOO':
    return loop(
      {...state, initStarted: true},
      { type: "mycommand1",
        actionCreator: myactioncreator
      })
    );
```

I'm not sure this is doable or even a good idea, but somehow I feel the need to separate the definition of the commands and the execution of the commands. I don't want my reducers to specify the execution of the commands. Also in some cases I feel the need to have a command executor which can be configured with some initial state (such as a router object). So in that case the command executor function could be curried before passing it to install.

**Comment by bdwain** [comment]
I think what you're describing sounds more like [redux saga](https://redux-saga.js.org/) than redux-loop. It's a great library so it's worth checking out. But I think the idea of a separate executor goes against the core idea of redux loop, which is to treat side effects and state transitions the same (or as close to the same as possible). It's described a bit more in the intro of the [docs](https://redux-loop.js.org/). And there's also plenty of material about [the elm architecture](https://guide.elm-lang.org/architecture/), which redux itself is based on, and redux loop fills in the missing pieces of.

> Synchronous state transitions caused by returning a new state from the reducer in response to an action are just one of all possible effects an action can have on application state.

As an example of where redux loop can help simplify your app, imagine you're making a page with a button, which when clicked, fetches some data. You want to show a loading state while the request is pending.

You could do something like this:
```js
function reducer(state = initialState, action){
  switch(action.type){
    case 'BUTTON_CLICKED':
      return loop({...state, loading: true}, {type: 'FETCH_DATA', id: state.id, actionCreator: myAc});
    default:
      return state;
  }
}

function executor(cmd){
  switch(cmd.type){
    case 'FETCH_DATA':
      return fetchData(cmd.id).then(cmd.actionCreator);
    default:
      return null;
  }
}
```

but redux-loop instead is focused on handling related logic together, whether it's a state transition or triggering some impure side-effect.

```js
function reducer(state = initialState, action){
  switch(action.type){
    case 'BUTTON_CLICKED':
      return loop({...state, loading: true}, Cmd.run(fetchData, {
         successActionCreator: myAc,
         args: [state.id]
      }));
    default:
      return state;
  }
}
```

This way, you're defining what happens in response to a button click in one spot, and also what happens next. You can still reuse fetchData (the side effect) in a different spot if you want to trigger a fetch via some other method. And you don't have to only handle BUTTON_CLICKED in a single reducer if things are organized in a way that different reducers might be concerned with the button being clicked. But the general idea behind redux loop is that the call to fetchData and setting loading to true are both just things that happen in response to a button being clicked, and they do not need to be logically separated just because one is a state change and the other is a side effect.

This pattern often seems weird at first, especially if you've been using redux for a while. I think it's kind of similar to how people are used to separating their javascript and html before they start using react. 

Let me know if you have more questions!

**Comment by jonaskello** [comment]
I've actually used redux-saga on a fairly large project. It works but it is quite hard to control. On my current project I am using elm-like fractal design for the reducers. So I nest them and nest the dispatch functions (manually). I don't think redux-saga is a good fit for that, I need the functionality of `Cmd.map` so the action creator functions become nested.

So looking at this example:

```ts
function reducer(state = initialState, action){
  switch(action.type){
    case 'BUTTON_CLICKED':
      return loop({...state, loading: true}, Cmd.run(fetchData, {
         successActionCreator: myAc,
         args: [state.id]
      }));
    default:
      return state;
  }
}
```

The `fetchData` function passed to Cmd.run here is actually a side-effectul function, not a description of the side-effect. I have not done any projects in elm but I've read extensively about it and from what I understand the elm language has no way to express side-effects. So in elm the above example would be impossible to write? Instead in elm the commands would have to be passed as mere data descriptors of the command, instead of combining the command and the effectful function together into one object (which to me feels a lot like OO). Is that a correct understanding how it works in elm? If it is, then what I want to do is exactly like it works in elm.

Maybe I have misunderstood something how commans elm works. If you have any good links that explains the internal workings of commands in elm that would be very helpful :-).

**Comment by bdwain** [comment]
Ah yea if you want a fractal pattern then Cmd.map is helpful for that. 

While `fetchData` is a function with side effects, returning it as part of a Cmd is basically just a description of the side effect. it does not run the side effect. We never say `fetchData()` in our code. [Cmd.run just returns an object](https://github.com/redux-loop/redux-loop/blob/master/src/cmd.js#L179), and one of the properties (func) is the function to run. But it does not get run until the store gets the Cmd and runs it after the reducer has finished. So it is a description of a side effect and what to do with the result. Your reducer is still a pure function if you return a Cmd.

Elm is basically the same way in that you don't execute the side effect yourself. You give the runtime (like the loop-enhanced redux store) a description of the side effect (like a loop Cmd) to run and what to do with the response. The only difference is that in javascript, there is no elm runtime, so your descriptions (Cmds) describe functions you wrote yourself, rather than a declarative http library (or whatever side effect type you want to run) like the ones in Elm.

Some good examples of elm are at https://guide.elm-lang.org/architecture/effects/http.html and http://toreto.re/tea/

**Comment by bdwain** [comment]
I think the above example in elm would look something like this (though i'm a bit rusty)

```elm
fetchData : String -> Cmd Msg
fetchData id =
  let
    url =
      "https://api.example.com/items/" ++ id

    request =
      Http.get url decodeDataObject
  in
    Http.send NewData request

decodeDataObject : Decode.Decoder String
decodeDataObject =
  Decode.at ["data", "property"] Decode.string

update : Msg -> Model -> (Model, Cmd Msg)
update msg model =
  case msg of
    ButtonClicked ->
      ({ model | loading = True }, fetchData model.id)

    NewData (Ok newData) ->
      ( { model | loading = False, data = newData }, Cmd.none)

    NewData (Err _) ->
      ({ model | loading = False, error = True }, Cmd.none)
```

**Comment by jonaskello** [comment]
Yes, I follow on that. My point was that even though the effect is not executed by the reducer, it is returning an object which has the actual effect function rather than a pure data record. So in the example, what you return with Cmd.run is something like:

```ts
{
  type: "run"
  function: (...) => { the actual code to run the fetch }
}
```

While I would prefer this:

```ts
{
  type: "fetch"
  url: "http://foo.com"
}
```

It is not so much different, just that the second object feels more pure since it is pure data. But I do get the fact that the first object is more pragmatic since it allows you to do anything with a single type of command.

To compare with actions, at one point I had an architecture that dispatched functions that could be applied to state, something like `dispatch((state) => { return {foo: bar, ...state}})`. So it did not execute the action, it just dispatched it and the reducer just applied the function to the state. So we could say it was just a description of the state transition. The upside of this is that there was no need for action creators of different types, switch statements in the reducer etc. However one of the problems with this approach was that there were no easy way to log what was going on since logging functions give very litte information. I think this is also true about logging the commands above. If I would log a `Cmd.run` command like the first object above, it would not really tell me what is going on. If the command is pure data and has a specific type, like the second object above, I could log it to see exactly what is going on. Also if we have pure data descriptors, then the description of the effect is fully separated from the application of the effect. With Cmd.run the the description and application are coupled.

Anyway, I'm now a happy user of redux-loop :-). I sattled on a pattern like this:

First I have a library of specific commands, for example I have a LocalStorage library like this:

```ts
import { ActionCreator, Action } from "redux";
import { RunCmd, Cmd } from "redux-loop";

export function setItem<A extends Action>(
  name: string,
  value: string,
  successActionCreator?: ActionCreator<A>
): RunCmd<A> {
  return Cmd.run(() => localStorage.setItem(name, value), { successActionCreator });
}
```

Which makes the reducer look like this:

```ts
export function reducer(
  state: Foo,
  action: Actions.Action
): Foo | Loop<Foo, Actions.Action> {
  switch (action.type) {
    case "Bar":
      return loop(state, LocalStorage.setItem("foo", "bar"));
    default:
      exhaustiveCheck(action);
      return state;
  }
}
```

I feel the upside here is that the reducer do not care what `LocalStorage.setItem()` produces. So I in the future I could switch to an implementation where `LocalStorage.setItem()` returns a pure data record instead of a `Cmd.run` command and I would not have to change any reducer code.

Also with this approach the commands are more explicit. With `Cmd.run` there is no way to tell if the effect should have no action creators, just a `successActionCreator` or just a `failureActionCreator` or both. Altough this could be considered less flexible I feel it is more descriptive to require exactly which  actionCreators makes sense for a particular command.

**Comment by jonaskello** [comment]
Btw, I'm currently working on implementing something similar to elm subscriptions. For example I would like to subscribe to a local storage key value changes. Do you know if there is any existing work on subscriptions in the javascript world?

**Comment by bdwain** [comment]
Interesting pattern! I see what you mean now. I’m glad you found something that works for you. 

FYI there’s an open issue about adding a redux loop extension to redux devtools which would log cmds among other things. Not sure if that would help at all but I’d like to add that at some point. 

As for subscriptions,  Nothing off the top of my head. There are connected components from react-redux for subscribing to state changes but that’s the only prebuilt one I know. Otherwise you might need to explclty set up some sort of pub-sub model or an eventemitter or something for each subscription you want to create.

**Comment by jonaskello** [comment]
Interestingly I found [this package](https://github.com/stewartml/side-effects) which seems to treat the commands similar to what I describe above. Although I'll stick with redux-loop for now :-).
