### ISSUE TITLE
successActionCreator/failActionCreator should also accept an action object

### ISSUE THREAD

**Issue by stavalfi** [redux-loop/redux-loop#201]
## Suggestion

My suggestion is to able to pass an action object to `successActionCreator` and `failActionCreator` in the same way we give them an action-creator (function).

```javascript
// reducer code:
return Cmd.run(myFunction1, {
    successActionCreator: { type: 'action1' },
    args: ['param']
});
```

## Current behavior

```javascript
// reducer code:
return Cmd.run(myFunction1, {
    successActionCreator: ()=>({ type: 'action1' }),
    args: ['param']
});
```

## Limitation / Negative Implications

To test the above code, I must use a pre-defined function which is accessible from the tests files also.
Sometimes, it is not possible because the action-creator function is a closure (the action-creator function is defined at runtime). 

Why the action-creator function sometimes needs to be created at runtime? Because it depends on variables that will not be pass from `myFunction1`:

```javascript
// reducer code:
return Cmd.run(myFunction1, {
    successActionCreator: ()=>({ type: 'action1' , myParam1: someVariable}),
    args: ['param']
});
```

The result is a failing test:
```javascript
test('failing test', t => {
    const cmd = Cmd.run(myFunction1, {
        successActionCreator: () => ({type: 'action1', myParam1: someVariable}),
        args: ['param']
    });
    t.deepEqual(myReducer(someState,someAction), cmd);
});
```

It means that an action-creator function can't have any params accept the result of the invoked function [My opinion: This limitation is too restricting].

Action creators can have parameters, as Redux docs mention:
https://redux.js.org/advanced/asyncactions#synchronous-action-creators
https://redux.js.org/advanced/asyncactions#actions-js-asynchronous

## Solution

Not legal due to the current behavior:
```javascript
const myActionCreator1 = param1 => ({ type: 'action1' , myParam1: param1});
return Cmd.run(myFunction1, {
    successActionCreator: myActionCreator1(someVariable),
    args: ['param']
});
```

## Unsolved questions

1. If `successActionCreator`/`failActionCreator` accepts objects, what should `Cmd.run` do with the return value of `myFunction1`? 
My suggestion: the user can choose between:
```javascript
const myActionCreator1 = param1 => ({ type: 'action1' , myParam1: param1});
return Cmd.run(myFunction1, {
    successActionCreator: returnValue => myActionCreator1(someVariable,returnValue),
    args: ['param']
});
```
```javascript
const myActionCreator1 = param1 => ({ type: 'action1' , myParam1: param1});
return Cmd.run(myFunction1, {
    successActionCreator: () => myActionCreator1(someVariable),
    args: ['param']
});

// which is the same as:

const myActionCreator1 = param1 => ({ type: 'action1' , myParam1: param1});
return Cmd.run(myFunction1, {
    successActionCreator: myActionCreator1(someVariable),
    args: ['param']
});
```

**Comment by bdwain** [comment]
Sorry for the delayed response @stavalfi.

I think allowing a user to pass an object to successActionCreator would cause confusion, since the name pretty clearly indicates it should be a function. There would also be no way to access the result of myFunction1, so I'm not sure what the point is. It would basically just be dispatching a predefined action as soon as that side effect finishes. If that's really what you want to do, you can already do that without needing simulation anyway.

```js
//reducer.js

const myVariable = 123;
const runCmd = Cmd.run(myFunction1, {
    args: ['param']
});

return Cmd.list([
   runCmd,
   Cmd.action(myActionCreator1(myVariable))
], {sequence: true});
```

If you need access to the result of myFunction1 and also want to pass in another parameter, then I think your best option is to define a function inline like you did above

```js
successActionCreator: returnValue => myActionCreator1(someVariable,returnValue)
```

Have you seen [Cmd simulation](https://redux-loop.js.org/docs/tutorial/Testing.html#simulating-cmd-objects)? I think it would help address the issues you had with testing these Cmds.

**Comment by bdwain** [comment]
Closing for now. I can reopen if needed.
