### ISSUE TITLE
Calls to Cmd.run that return a promise without a failActionCreator should throw an error on failure

### ISSUE THREAD

**Issue by D1plo1d** [redux-loop/redux-loop#221]
These 2 lines appears to log but not throw failures when running an async function:

* https://github.com/redux-loop/redux-loop/blob/master/src/cmd.js#L43
* https://github.com/redux-loop/redux-loop/blob/master/src/cmd.js#L50

I expected async functions to throw errors when a failActionCreator is not supplied. That would be consistent with how errors are thrown for synchronous functions without failActionCreator handlers ([cmd.js#L58](https://github.com/redux-loop/redux-loop/blob/master/src/cmd.js#L58)).

**Comment by bdwain** [comment]
Rejected promises are swallowed (but logged) since things like failed requests are not uncommon, and if you are not going to do anything when the request fails, we shouldn't force you to provide a handler for that. 

A thrown exception seems like it should not be swallowed though, since that's usually some kind of fixable error (from a development perspective).

I can see how that's confusing, but redux loop never required you to handle failures before, and I think doing that now would be a big breaking change that wouldn't really solve a pressing problem. We log the error, but if you don't provide a handler that's all we can do without crashing the application, and I'm not sure that's the right thing to do from the library's perspective.

I suppose we could support some sort of strict mode where we would crash (or just warn) if you do not provide a failure handler. Does that sound reasonable?

**Comment by D1plo1d** [comment]
Yes, I can see the argument for backwards compatibility. I'm experimenting with using redux-loop as the backend server-side in memory store for a IOT device where a rejected promise may be an irrevocable error in a complicated state machine and should crash the server (fail fast) may matter a lot more then in a simpler client-side redux-loop.

As a workaround: I can create a `FatalError` action and set that as the FailActionCreator anywhere I don't handle the rejection and then throw from a reducer on `FatalError`.

**Comment by bdwain** [comment]
I see. Yea that sounds like a pretty specific use case, but I think your approach makes sense and will work. 

I'm going to close this for now as I don't think there are any changes to make for now.
