### ISSUE TITLE
Overhead with effectTypes.NONE

### ISSUE THREAD

**Issue by crobi** [redux-loop/redux-loop#62]
Every time you dispatch an action with no effects, `redux-loop` creates a new "no-effect" object and starts a promise that doesn't do anything on resolve. Could this be optimized away?

In my application I'm creating ~100 pure (side-effect-free) actions per second, and these empty promises show up in the profile.

**Comment by lukewestby** [comment]
This should definitely get fixed. There's no real reason to be creating those Promises other than it was easier to think about when we were trying to get the lib out the door.

**Comment by lukewestby** [comment]
This optimization is going to get rolled into the effects API rework discussed in #66 

Any time an effect which will ultimately become a no-op is detected it will be ignored entirely. This includes `none`, but also empty `batch`es and `batch`es consisting entirely of `none`s, other empty `batch`es or otherwise no-op effects.

**Comment by lukewestby** [comment]
I'm pretty sure this is now handled by the next version

https://github.com/redux-loop/redux-loop/pull/95

We'll be sure all the necessary optimizations are there before doing a final release
