### ISSUE TITLE
How to achieve Effects.call or constant in redux-loop@3

### ISSUE THREAD

**Issue by mauron85** [redux-loop/redux-loop#99]
Sorry for posting question here rather than stackoverflow, but the tag redux-loop is not available yet.

I'm trying to migrate to redux-loop@3 and there is no Effects.constant or Effect.call. According to release announcement

>Moving forward we're going to avoid special-case things like Effects.call. All of these things can be expressed as either a Task or a Port

But didn't figured out how can I migrate following reducer. It creates new effect by calling action **connect**.

```
  [SCRIPT_LOAD_SUCCESS]: (state, action) => {
    if (state.script !== action.payload.hash) { return state; }
    return loop(
      { ...state, status: 'LOADED' },
      (state.autoConnect) ?
        Effects.constant(connect()) :
        Effects.none()
    );
  },
```

```
export function connect(url) {
  return {
    type: SOCKET_CONNECT,
    payload: { url }
  };
}
```

Advice is very welcome here and hopefully it will also help others, not to ask same question again.
Many thanks for amazing library.

**Comment by lukewestby** [comment]
You can quickly replace `Effects.call` with `Task.succeed(url).perform(connect)`. However, I recommend refactoring your app's logic over time to eliminate the use of `Effects.call` or this replacement. We found that `Effects.call` leads to unmaintainable trails of inappropriately coupled reducer branches, which is why I decided to remove it.
